In [1]:
import requests
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import sys
import re
import os

from datetime import datetime, timedelta

In [2]:
!pip install chromedriver-py

Requirement already satisfied: chromedriver-py in /home/nwzish/anaconda3/envs/fl/lib/python3.8/site-packages (92.0.4515.43)

In [2]:
from webdriver_manager.chrome import ChromeDriverManager

In [51]:
os.getcwd()

'/home/nwzish/freelance/kedia/0nProgress3/scrapping/code'

In [3]:
driver = webdriver.Chrome(os.getcwd()+'/chromedriver')

In [55]:
driver2 = webdriver.Chrome(os.getcwd()+'/chromedriver')

In [56]:
driver2.close()

In [4]:
# driver2 = webdriver.Chrome('chromedriver')

In [5]:
START_DATE = '2021/06/15'
END_DATE= '2021/06/18'
STOCK_CODE_START = 1
STOCK_CODE_END = 10

In [6]:
def get_date_list(sd,ed):
    _sd = datetime.strptime(sd, '%Y/%m/%d')
    _ed = datetime.strptime(ed, '%Y/%m/%d')
    
    if _sd > _ed:
        sys.exit("Start date is more than end date")

    _date_list = []
    
    while _sd<=_ed:
        _date_list.append(_sd.strftime('%Y/%m/%d'))
        _sd = _sd + timedelta(days=1)
        
    return _date_list

In [66]:
# def get_stock_code_list(scs,sce):

#     if scs>sce:
#         sys.exit("stock code start is more than stock code end")
#     _stock_code_list = []
#     while scs<=sce:
#         sc = str(scs)
#         sc = '0'*(5-len(sc))+sc
#         _stock_code_list.append(sc)
#         scs += 1
#     return _stock_code_list

In [7]:
stock_code_list = get_stock_code_list(STOCK_CODE_START,STOCK_CODE_END)

In [9]:
date_list = get_date_list(START_DATE,END_DATE)

In [7]:
list_URL = 'https://www.hkexnews.hk/sdw/search/stocklist.aspx?sortby=stockcode&shareholdingdate=20210619'
URL = "https://www.hkexnews.hk/sdw/search/searchsdw.aspx"
driver.get(URL)

In [8]:
driver.execute_script("document.getElementById('txtShareholdingDate').value='2021/05/17'")

In [9]:
driver.execute_script("document.getElementById('txtStockCode').value='60'")

In [10]:
driver.execute_script("document.getElementById('txtStockCode').value='60'")
driver.find_element_by_id('btnSearch').click()

In [28]:
summary = driver.find_element_by_css_selector('#pnlResultSummary')

In [33]:
aa = driver.find_element_by_css_selector('#pnlResultSummary > div > div:nth-child(2) > div.shareholding > div.value')

In [11]:
soup = BeautifulSoup(driver.page_source,'html.parser')

In [27]:
stock_table = soup.select_one('table').select_one('tbody').select('tr')

In [67]:
def get_stock_code_list(_date):
    limit = 9999
    _date = _date.replace('/','')
    list_URL = 'https://www.hkexnews.hk/sdw/search/stocklist.aspx?sortby=stockcode&shareholdingdate='+_date
    driver2 = webdriver.Chrome(os.getcwd()+'/chromedriver')
    driver2.get(list_URL)
    soup = BeautifulSoup(driver2.page_source,'html.parser')
    stock_table = soup.select_one('table').select_one('tbody').select('tr')
    
    _stock_list = []
    for r in stock_table:
        stock_code = r.select_one('td').get_text().replace('\n','').strip()
        
        if int(stock_code)>limit:
            break
        _stock_list.append(stock_code)
    driver2.close()
    
    return _stock_list

In [68]:
get_stock_code_list('2021/06/12')[-100:]

['09011',
 '09022',
 '09031',
 '09047',
 '09067',
 '09072',
 '09074',
 '09077',
 '09078',
 '09081',
 '09085',
 '09086',
 '09088',
 '09091',
 '09096',
 '09101',
 '09115',
 '09126',
 '09140',
 '09141',
 '09167',
 '09169',
 '09170',
 '09173',
 '09181',
 '09186',
 '09187',
 '09191',
 '09600',
 '09608',
 '09616',
 '09618',
 '09626',
 '09633',
 '09666',
 '09668',
 '09677',
 '09688',
 '09698',
 '09803',
 '09804',
 '09805',
 '09806',
 '09807',
 '09809',
 '09810',
 '09812',
 '09814',
 '09817',
 '09820',
 '09826',
 '09834',
 '09836',
 '09845',
 '09846',
 '09888',
 '09900',
 '09901',
 '09906',
 '09908',
 '09909',
 '09911',
 '09913',
 '09916',
 '09918',
 '09919',
 '09922',
 '09923',
 '09926',
 '09928',
 '09929',
 '09933',
 '09936',
 '09938',
 '09939',
 '09958',
 '09959',
 '09961',
 '09963',
 '09966',
 '09968',
 '09969',
 '09977',
 '09978',
 '09979',
 '09982',
 '09983',
 '09986',
 '09987',
 '09988',
 '09989',
 '09990',
 '09991',
 '09992',
 '09993',
 '09995',
 '09996',
 '09997',
 '09998',
 '09999']

In [37]:
len(_stock_list)

5218

In [34]:
int(ll.select_one('td').get_text().replace('\n','').strip())

1

In [46]:
summary = soup.find_all('div',id='pnlResultSummary')

1

In [144]:
def get_summary_data(summary):
    _summary_category = []
    _shareholding = []
    _number_of_participants = []
    _percent_of_participants = []
    summary_data = {}
    for s in summary[0].select('div.ccass-search-datarow'):

        sc = s.select_one('div.summary-category').get_text()
        summary_data[sc] = []
        _summary_category.append(sc)
    #     print(sc)
        sh = s.select_one('div.shareholding').select_one('.value').get_text()
    #     print(sh)
    #     print(int(sh.select_one('.value').get_text().replace(',','')))
        _shareholding.append(sh)
        summary_data[sc].append(sh)
        nop = s.select_one('div.number-of-participants').select_one('.value').get_text()
    #         print(e.select_one('.value').get_text())
        _number_of_participants.append(nop)
        summary_data[sc].append(nop)
        pop = s.select_one('div.percent-of-participants').select_one('.value').get_text()
    #     for e in pop[1:]:
        _percent_of_participants.append(pop)
        summary_data[sc].append(pop)
    #         print(e.select_one('.value').get_text())
    #     print(s.select('div.number-of-participants')[1].select('div.value')[0].get_text())
    #     print(s)

    luf = re.sub('\s+',' ',summary[0].select_one('div.summary-header').get_text().replace('\n','').strip())
    _tluf = int(summary[0].select_one('div.summary-value').get_text().replace(',',''))
    summary_data[luf] = _tluf

    print(luf)
    print(_summary_category)
    print(_shareholding)
    print(_number_of_participants)
    print(_percent_of_participants)
    print(_total_number_of_issued_shares)
    summary_data

    for k in summary_data.keys():
        summary_data[k] = [summary_data[k]]

    summary_data

Total number of Issued Shares/Warrants/Units (last updated figure)
['Market Intermediaries', 'Consenting Investor Participants', 'Non-consenting Investor Participants', 'Total']
['802,870,656', '106,000', '31,993,669', '834,970,325']
['198', '3', '55', '256']
['58.96%', '0.00%', '2.34%', '61.30%']
1361618242

{'Market Intermediaries': [['802,870,656', '198', '58.96%']],
 'Consenting Investor Participants': [['106,000', '3', '0.00%']],
 'Non-consenting Investor Participants': [['31,993,669', '55', '2.34%']],
 'Total': [['834,970,325', '256', '61.30%']],
 'Total number of Issued Shares/Warrants/Units (last updated figure)': [1361618242]}

In [145]:
pd.DataFrame(summary_data)

,Market Intermediaries,Consenting Investor Participants,Non-consenting Investor Participants,Total,Total number of Issued Shares/Warrants/Units (last updated figure)
0,"[802,870,656, 198, 58.96%]","[106,000, 3, 0.00%]","[31,993,669, 55, 2.34%]","[834,970,325, 256, 61.30%]",1361618242

In [116]:
def extract_summary(summary):

    _shareholding = []
    _number_of_participants = []
    _percent_of_participants = []

    for s in summary:
        sc = s.select_one('div.summary-category').get_text()
        print(sc)
        sh = s.select('div.shareholding')
        for e in sh[1:]:
    #         print(int(e.select_one('.value').get_text().replace(',','')))
            _shareholding.append(e.select_one('.value').get_text())
        nop = s.select('div.number-of-participants')
        for e in nop[1:]:
    #         print(e.select_one('.value').get_text())
            _number_of_participants.append(e.select_one('.value').get_text())
        pop = s.select('div.percent-of-participants')
        for e in pop[1:]:
            _percent_of_participants.append(e.select_one('.value').get_text())
    #         print(e.select_one('.value').get_text())
    #     print(s.select('div.number-of-participants')[1].select('div.value')[0].get_text())
    _total_number_of_issued_shares = int(summary[0].select_one('div.summary-value').get_text().replace(',',''))
    print(_shareholding)
    print(_number_of_participants)
    print(_percent_of_participants)
    print(_total_number_of_issued_shares)

In [117]:
extract_summary(summary)

Market Intermediaries
['802,870,656', '106,000', '31,993,669', '834,970,325']
['198', '3', '55', '256']
['58.96%', '0.00%', '2.34%', '61.30%']
1361618242

In [13]:
table = soup.find_all('div',id='pnlResultNormal')[0].select('tr')

In [14]:
# table = details[0].select('tr')

In [15]:
table[1]

<tr>
<td class="col-participant-id">
<div class="mobile-list-heading">Participant ID:</div>
<div class="mobile-list-body">B01324</div>
</td>
<td class="col-participant-name">
<div class="mobile-list-heading">Name of CCASS Participant (* for Consenting Investor Participants ):</div>
<div class="mobile-list-body">FUNDERSTONE SECURITIES LTD</div>
</td>
<td class="col-address">
<div class="mobile-list-heading">Address:</div>
<div class="mobile-list-body">ROOM 1802 18/F CAPITAL CENTRE NO. 151 GLOUCESTER ROAD WANCHAI HONG KONG</div>
</td>
<td class="col-shareholding text-right">
<div class="mobile-list-heading">Shareholding:</div>
<div class="mobile-list-body">79,388,596</div>
</td>
<td class="col-shareholding-percent text-right">
<div class="mobile-list-heading">% of the total number of Issued Shares/ Warrants/ Units:</div>
<div class="mobile-list-body">30.58%</div>
</td>
</tr>

In [202]:
table[0]

<tr>
<th class="col-participant-id tablesorter-header tablesorter-headerUnSortedAsc" data-column-class="col-participant-id" data-sort-by="participantid" data-sort-dir-default="asc" tabindex="0">Participant ID</th>
<th class="col-participant-name tablesorter-header tablesorter-headerUnSortedAsc" data-column-class="col-participant-name" data-sort-by="participantname" data-sort-dir-default="asc" tabindex="0">Name of CCASS Participant<br/>(* for Consenting Investor Participants )</th>
<th class="col-address sorter-false" data-column-class="col-address">Address</th>
<th class="col-shareholding tablesorter-header tablesorter-headerDesc" data-column-class="col-shareholding" data-sort-by="shareholding" data-sort-dir-default="desc" tabindex="0">Shareholding</th>
<th class="col-shareholding-percent sorter-false text-right" data-column-class="col-shareholding-percent" tabindex="0">
                                                % of the total number of Issued Shares/ Warrants/ Units

                                        </th></tr>

In [206]:
def get_column_names(_table):
    _column_name = []
    for c in _table[0].select('th'):
        _column_name.append(c.get_text().strip())
    
    return _column_name

In [218]:
def get_table_data(_table):
    
    
    _participant_id = []
    _name_of_ccass = []
    _address = []
    _shareholding = []
    _percent_of_total_issued_shares = []
    
    for r in _table[1:]:

        cells = r.select('td')
        _participant_id.append(cells[0].select_one('div.mobile-list-body').get_text() or '')
        _name_of_ccass.append(cells[1].select_one('div.mobile-list-body').get_text() or '')
        _address.append(cells[2].select_one('div.mobile-list-body').get_text() or '')
        _shareholding.append(cells[3].select_one('div.mobile-list-body').get_text() or '')
        _percent_of_total_issued_shares.append(cells[4].select_one('div.mobile-list-body').get_text() or '') 

#     print(_participant_id)
#     print(_name_of_ccass)
#     print(_address)
#     print(_shareholding)
#     print(_percent_of_total_issued_shares)
    tdl = [_participant_id,_name_of_ccass,_address,_shareholding,_percent_of_total_issued_shares]
    tcn = get_column_names(_table)
    
    td = {}
    for i in range(5):
        td[tcn[i]] = tdl[i]
    
    return td

In [219]:
get_table_data(table)

{'Participant ID': ['C00019',
  'C00100',
  'C00010',
  'C00015',
  'A00004',
  'C00018',
  'C00004',
  'C00093',
  'B01161',
  'C00074',
  'A00003',
  'C00039',
  'C00033',
  'B01274',
  'B01353',
  'B01590',
  'B01451',
  'C00041',
  'B01284',
  'C00042',
  'C00028',
  'C00058',
  'C00037',
  'B01089',
  'B01727',
  'B01129',
  'B01130',
  'B01668',
  'B01347',
  'B01955',
  'C00003',
  'B01345',
  'B01183',
  'B01121',
  'C00040',
  'B01118',
  'B01086',
  'B01695',
  'C00036',
  'C00002',
  'B01491',
  'B01842',
  'C00048',
  'B01246',
  'B01584',
  'B01939',
  'C00016',
  'B01272',
  'C00026',
  'B01610',
  'B01762',
  'B01228',
  'B01565',
  'B01428',
  'B01724',
  'B01143',
  'B01673',
  'B01115',
  'B01264',
  'B01133',
  'B01623',
  'B01323',
  'B01642',
  'B01904',
  'B01459',
  'B01497',
  'C00088',
  'B01929',
  'B01224',
  'B01700',
  '',
  'B01654',
  'B01494',
  'B01356',
  'B01267',
  'B01372',
  'B01843',
  'B01890',
  'B01209',
  'B01715',
  'B01511',
  'B01423',
  'C00095',
  '',
  'B01148',
  'B01555',
  'B01320',
  'B01324',
  'B01425',
  'B01556',
  'B01567',
  'B01212',
  'B01787',
  'B01373',
  'B01198',
  'B01169',
  'B01217',
  'B01818',
  'B01676',
  'B01445',
  'B01289',
  'B01275',
  'B01849',
  'B01416',
  'B01493',
  'B01551',
  'B01609',
  'B01645',
  'B01519',
  'B01230',
  'B01231',
  'B01119',
  'B01271',
  'B01905',
  'B01421',
  'B01481',
  'B01779',
  'B01858',
  'B01581',
  'B01238',
  'B01563',
  'B01606',
  'B01508',
  'B01158',
  'B01343',
  'B01252',
  'B01649',
  'B01362',
  'B01660',
  'B01706',
  'B01708',
  'B01784',
  'B01829',
  'B01948',
  'B01298',
  'B01450',
  'B01184',
  'B01813',
  'B01875',
  'B01885',
  'B01455',
  'B01696',
  'B01699',
  'B01947',
  'B01967',
  'B01540',
  'B01514',
  'B01809',
  'B02132',
  'B01350',
  'B01749',
  'B01265',
  'B01417',
  'B01520',
  'B01646',
  'B01665',
  'B01679',
  'B01415',
  'B01712',
  'B01743',
  'B01773',
  'B01777',
  'B01988',
  'B01340',
  'B01173',
  'B01351',
  'B01433',
  'B01454',
  'B01575',
  'B01615',
  'B01661',
  'B01893',
  'B01141',
  'B01144',
  'B01181',
  'B01413',
  'B01438',
  'B01470',
  'B01483',
  'B01564',
  'B01601',
  'B01789',
  'B01900',
  'B01940',
  'B01962',
  'B01523',
  '',
  'B01213',
  'B01253',
  'B01290',
  'B01376',
  'B01543',
  'B01767',
  'B01794',
  'B01826',
  'B01848',
  'B01938',
  'B01986',
  'B01769',
  'B01240',
  'B01407'],
 'Name of CCASS Participant(* for Consenting Investor Participants )': ['THE HONGKONG AND SHANGHAI BANKING',
  'JPMORGAN CHASE BANK, NATIONAL',
  'CITIBANK N.A.',
  'DBS BANK (HONG KONG) LTD',
  'CHINA SECURITIES DEPOSITORY AND CLEARING',
  'HANG SENG BANK LTD',
  'MUFG BANK, LTD.',
  'BNP PARIBAS SECURITIES SERVICES',
  'UBS SECURITIES HONG KONG LTD',
  'DEUTSCHE BANK AG',
  'CHINA SECURITIES DEPOSITORY AND CLEARING',
  'STANDARD CHARTERED BANK (HONG KONG) LTD',
  'BANK OF CHINA (HONG KONG) LTD',
  'MORGAN STANLEY HONG KONG SECURITIES LTD',
  'UOB KAY HIAN (HONG KONG) LTD',
  'INTERACTIVE BROKERS HONG KONG LTD',
  'GOLDMAN SACHS (ASIA) SECURITIES LTD',
  'OCBC WING HANG BANK LTD',
  'HANG SENG SECURITIES LTD',
  'CMB WING LUNG BANK LTD',
  'NANYANG COMMERCIAL BANK LTD',
  'CHINA CITIC BANK INTERNATIONAL LTD',
  'SHANGHAI COMMERCIAL BANK LTD',
  'HSBC BROKING SECURITIES (HONG KONG) LTD',
  'ICBC (ASIA) SECURITIES LTD',
  'WOCOM SECURITIES LTD',
  'BOCI SECURITIES LTD',
  'BRIGHT SMART SECURITIES INTERNATIONAL',
  'CGS-CIMB SECURITIES (HONG KONG) LTD',
  'FUTU SECURITIES INTERNATIONAL',
  'THE BANK OF EAST ASIA LTD',
  'PHILLIP SECURITIES (HONG KONG) LTD',
  'CHONG HING SECURITIES LTD',
  'SG SECURITIES (HK) LTD',
  'INDUSTRIAL AND COMMERCIAL BANK OF CHINA',
  'EAST ASIA SECURITIES CO LTD',
  'SUN HUNG KAI INVESTMENT SERVICES LTD',
  'DAH SING SECURITIES LTD',
  'CHINA CONSTRUCTION BANK (ASIA)',
  'BANK OF COMMUNICATIONS TRUSTEE LTD',
  'CREDIT SUISSE SECURITIES (HONG KONG) LTD',
  'BOCOM INTERNATIONAL SECURITIES LTD',
  'CHIYU BANKING CORPORATION LTD',
  'ROCTEC SECURITIES CO LTD',
  'CHIEF SECURITIES LTD',
  'SOOCHOW SECURITIES INTERNATIONAL',
  'DBS BANK LTD',
  'FB SECURITIES (HONG KONG) LTD',
  'CHONG HING BANK LTD',
  'KGI ASIA LTD',
  'DBS VICKERS (HONG KONG) LTD',
  'CITIC SECURITIES BROKERAGE (HK) LTD',
  'GUOTAI JUNAN SECURITIES (HONG KONG) LTD',
  'HIP HING SECURITIES LTD',
  'RAMON INVESTMENT CO LTD',
  'HAITONG INTERNATIONAL SECURITIES CO LTD',
  'FULBRIGHT SECURITIES LTD',
  'SHENWAN HONGYUAN SECURITIES (H.K.) LTD',
  'KIM ENG SECURITIES (HONG KONG) LTD',
  'RBC INVESTMENT SERVICES (ASIA) LTD',
  'TAI FUNG KUENTAI SECURITIES CO LTD',
  'DEUTSCHE SECURITIES ASIA LTD',
  'KMT SECURITIES LTD',
  'VALUABLE CAPITAL LTD',
  'IFAST SECURITIES (HK) LTD',
  'SINOPAC SECURITIES (ASIA) LTD',
  'CHINA MERCHANTS BANK CO LTD',
  'CHINA GALAXY INTERNATIONAL SECURITIES',
  'MERRILL LYNCH FAR EAST LTD',
  'REALINK FINANCIAL TRADE LTD',
  'YUNG KIT YI ALICE *',
  'CHINA INTERNATIONAL CAPITAL CORPORATION',
  'AUDREY CHOW SECURITIES LTD',
  'DELTA ASIA SECURITIES LTD',
  'WINFULL SECURITIES LTD',
  'FIRST WORLDSEC SECURITIES LTD',
  'TD KING SECURITIES LTD',
  'GUOSEN SECURITIES (HK) BROKERAGE CO LTD',
  'MASON SECURITIES LTD',
  'PRESIDENT SECURITIES (HONG KONG) LTD',
  'TAT LEE SECURITIES CO LTD',
  'PRUDENTIAL BROKERAGE LTD',
  'EFG BANK AG',
  'TONG WUN LING *',
  'CHINA MERCHANTS SECURITIES (HK) CO LTD',
  'ABN AMRO CLEARING HONG KONG LTD',
  'LUEN FAT SECURITIES CO LTD',
  'FUNDERSTONE SECURITIES LTD',
  'WELLFULL SECURITIES CO LTD',
  'LUK FOOK SECURITIES (HK) LTD',
  'PRIME SECURITIES LTD',
  'HENYEP SECURITIES LTD',
  'SOO PUI CHEN SECURITIES LTD',
  'CHRISTFUND SECURITIES LTD',
  'PO KAY SECURITIES & SHARES CO LTD',
  'PUBLIC FINANCIAL SECURITIES LTD',
  'TAIPING SECURITIES (HK) CO LTD',
  'I-ACCESS INVESTORS LTD',
  'TAI SHING STOCK INVESTMENT CO LTD',
  'VICTORY SECURITIES CO LTD',
  'SOUTH CHINA SECURITIES LTD',
  'SANFULL SECURITIES LTD',
  'CIS SECURITIES ASSET MANAGEMENT LTD',
  'VC BROKERAGE LTD',
  'YARDLEY SECURITIES LTD',
  'YUE XIU SECURITIES CO LTD',
  'WILBY SECURITIES LTD',
  'SELINA & CO LTD',
  'GOOD HARVEST SECURITIES CO LTD',
  'PACIFIC FOUNDATION SECURITIES LTD',
  'HONG KONG INTERNATIONAL SECURITIES LTD',
  'CELESTIAL SECURITIES LTD',
  'HANG TAI SECURITIES LTD',
  'ESSENCE INTERNATIONAL SECURITIES',
  'ONEPLATFORM SECURITIES LTD',
  'NEW REGION SECURITIES CO LTD',
  "LEE'S SECURITIES CO LTD",
  'YUANTA SECURITIES (HONG KONG) CO LTD',
  'KINGSWAY FINANCIAL SERVICES GROUP LTD',
  'TAI YIP STOCK CO LTD',
  'HUARONG INTERNATIONAL SECURITIES LTD',
  'EWARTON SECURITIES LTD',
  'SOUTHWEST SECURITIES (HK) BROKERAGE LTD',
  'SOLID KING SECURITIES LTD',
  'CELETIO INVESTMENTS LTD',
  'CORPORATE BROKERS LTD',
  'CINDA INTERNATIONAL SECURITIES LTD',
  'JOSPA INVESTMENT CO LTD',
  'GRANSING SECURITIES CO LTD',
  'MAN HON YEUNG SECURITIES LTD',
  'ROSA SECURITIES LTD',
  'FU YIP SECURITIES AND INVESTMENT CO LTD',
  'HUATAI FINANCIAL HOLDINGS (HONG KONG)',
  'CAITONG INTERNATIONAL SECURITIES CO LTD',
  'GET NICE SECURITIES LTD',
  'DL BROKERAGE LTD',
  'CHINA TONGHAI SECURITIES LTD',
  'CCB INTERNATIONAL SECURITIES LTD',
  'GUODU SECURITIES (HONG KONG) LTD',
  'EASTMONEY INTERNATIONAL SECURITIES LTD',
  'NATIONAL RESOURCES SECURITIES LTD',
  'HANTEC SECURITIES CO LTD',
  'MASTERLINK SECURITIES (HONG KONG)',
  'FUBON SECURITIES (HONG KONG) LTD',
  'YUNFENG SECURITIES LTD',
  'UPBEST SECURITIES CO LTD',
  'KARL-THOMSON SECURITIES CO LTD',
  'CHINA SYSTEM SECURITIES LTD',
  'MONEX BOOM SECURITIES (H.K.) LTD',
  'S. W. WOO & CO LTD',
  'TANG KEE SECURITIES LTD',
  'OCBC WING HANG SHARES BROKERAGE CO. LTD',
  'CHEE TAK SECURITIES LTD',
  'NORTH SEA SECURITIES LTD',
  'TAI NING STOCK CO LTD',
  'WINSOME STOCK CO LTD',
  'TAI FUNG SECURITIES LTD',
  'TARZAN STOCK & SHARES LTD',
  'WAH SANG SECURITIES LTD',
  'CEPA ALLIANCE SECURITIES LTD',
  'TOYO SECURITIES ASIA LTD',
  'DAIWA CAPITAL MARKETS HONG KONG LTD',
  'KOALA SECURITIES LTD',
  'LEHIN SECURITIES LTD',
  'RIFA SECURITIES LTD',
  'WING FUNG SECURITIES LTD',
  'HING WAI ALLIED SECURITIES LTD',
  'HAO TIAN INTERNATIONAL SECURITIES LTD',
  'MASTER TRADEMORE SECURITIES LTD',
  'KAM FAI SECURITIES CO LTD',
  'HERMES SECURITIES LTD',
  'WINCO SECURITIES CO LTD',
  'FE SECURITIES LTD',
  'TAK FUNG SHARES INVESTMENT CO LTD',
  'FOSUN HANI SECURITIES LTD',
  'CORE PACIFIC - YAMAICHI INTERNATIONAL',
  'KINGSTON SECURITIES LTD',
  'HUNG SING SECURITIES LTD',
  'BULLISH SECURITIES LTD',
  'ABCI SECURITIES CO LTD',
  'CSC SECURITIES (HK) LTD',
  'HO FUNG SHARES INVESTMENT LTD',
  'ORIENT SECURITIES (HONG KONG) LTD',
  'SOFI SECURITIES (HONG KONG) LTD',
  'CHINA SECURITIES (INTERNATIONAL)',
  'EVER-LONG SECURITIES CO LTD',
  'SEEN SIU LAM *',
  'MALAHON SECURITIES LTD',
  'STOCKWELL SECURITIES LTD',
  'SPS SECURITIES LTD',
  'PUBLIC SECURITIES LTD',
  'KWONG FAT HONG (SECURITIES) LTD',
  'NEW GALA SECURITIES CO LTD',
  'INTERCONTINENT SECURITIES CO LTD',
  'GF SECURITIES (HONG KONG) BROKERAGE LTD',
  'CATHAY SECURITIES (HONG KONG) LTD',
  'CHINA INDUSTRIAL SECURITIES',
  'HUAJIN SECURITIES (INTERNATIONAL) LTD',
  'ONE CHINA SECURITIES LTD',
  'TSUN CHI YUEN SECURITIES CO LTD',
  'WIN WONG SECURITIES LTD'],
 'Address': ['HSBC WEALTH BUSINESS SERVICES 8/F TOWER 2 & 3 HSBC CENTRE 1 SHAM MONG ROAD KOWLOON',
  '18/F TOWER 2 THE QUAYSIDE 77 HOI BUN ROAD KWUN TONG KOWLOON',
  '9/F CITI TOWER ONE BAY EAST 83 HOI BUN ROAD KWUN TONG KOWLOON',
  '7/F TWO HARBOUR SQUARE 180 WAI YIP STREET KWUN TONG KOWLOON',
  '17 TAIPING QIAO STREET XICHENG DISTRICT BEIJING CHINA',
  '16/F HANG SENG 113 113 ARGYLE STREET MONGKOK KOWLOON',
  '5/F AIA CENTRAL 1 CONNAUGHT ROAD CENTRAL HONG KONG',
  "21/F PCCW TOWER TAIKOO PLACE 979 KING'S ROAD QUARRY BAY HONG KONG",
  '52/F TWO INTERNATIONAL FINANCE CENTRE 8 FINANCE STREET CENTRAL HONG KONG',
  '51/F-66/F INTERNATIONAL COMMERCE CENTRE 1 AUSTIN ROAD WEST KOWLOON',
  '17 TAIPING QIAO STREET XICHENG DISTRICT BEIJING CHINA',
  '18/F STANDARD CHARTERED BANK TOWER MILLENNIUM CITY 388 KWUN TONG ROAD KWUN TONG KOWLOON',
  '11/F BANK OF CHINA CENTRE OLYMPIAN CITY 11 HOI FAI ROAD WEST KOWLOON',
  '46/F INTERNATIONAL COMMERCE CENTRE 1 AUSTIN ROAD WEST KOWLOON',
  '6/F HARCOURT HOUSE 39 GLOUCESTER ROAD HONG KONG',
  'SUITE 1512 TWO PACIFIC PLACE 88 QUEENSWAY HONG KONG',
  "68TH FLOOR CHEUNG KONG CENTER 2 QUEEN'S ROAD CENTRAL HONG KONG",
  'UNIT 1702 17/F EASTERN CENTRAL PLAZA 3 YIU HING ROAD SHAU KEI WAN HONG KONG',
  '16/F HANG SENG 113 113 ARGYLE STREET MONGKOK KOWLOON',
  'RM 1207-1209 12/F WING LUNG BANK CENTRE 636 NATHAN ROAD KOWLOON',
  '11/F BANK OF CHINA CENTRE OLYMPIAN CITY 11 HOI FAI ROAD WEST KOWLOON',
  "18/F DEVON HOUSE TAIKOO PLACE 979 KING'S ROAD QUARRY BAY HONG KONG",
  'C/O SECURITIES PROCESSING CENTRE LEVEL 23 TOWER 2 KOWLOON COMMERCE CENTRE 51 KWAI CHEONG ROAD KWAI CHUNG NEW TERRITORIES',
  "LEVEL 25 HSBC MAIN BUILDING 1 QUEEN'S ROAD CENTRAL HONG KONG",
  'LEVEL 16 TOWER 1 MILLENNIUM CITY 1 388 KWUN TONG ROAD KWUN TONG KOWLOON',
  'RM 1002 WING ON CENTRE 111 CONNAUGHT ROAD CENTRAL HONG KONG',
  "22/F GRAND MILLENNIUM PLAZA 181 QUEEN'S ROAD CENTRAL HONG KONG",
  '10/F WING ON HOUSE 71 DES VOEUX ROAD CENTRAL CENTRAL HONG KONG',
  'UNIT 2808B-2811 28/F WING ON CENTRE 111 CONNAUGHT ROAD CENTRAL HONG KONG',
  '11/F BANGKOK BANK BUILDING 14-20 BONHAM STRAND WEST SHEUNG WAN HONG KONG',
  '35/F BEA TOWER MILLENNIUM CITY 5 418 KWUN TONG ROAD KWUN TONG KOWLOON',
  '11/F UNITED CENTRE 95 QUEENSWAY HONG KONG',
  '2/F CHONG HING BANK CENTRE 24 DES VOEUX ROAD CENTRAL HONG KONG',
  "38/F 3 PACIFIC PLACE 1 QUEEN'S ROAD EAST HONG KONG",
  'LEVEL 16 TOWER 1 MILLENNIUM CITY 1 388 KWUN TONG ROAD KWUN TONG KOWLOON',
  'C/O BEA SETTLEMENT OPERATIONS DEPT-IOS 35/F BEA TOWER MILLENNIUM CITY 5 418 KWUN TONG ROAD KOWLOON',
  '42/F LEE GARDEN ONE 33 HYSAN AVENUE CAUSEWAY BAY HONG KONG',
  "SUITE 1910 19/F ISLAND PLACE TOWER 510 KING'S ROAD NORTH POINT HONG KONG",
  '20/F CCB CENTRE 18 WANG CHIU ROAD KOWLOON BAY KOWLOON',
  '16/F COS CENTRE 56 TSUN YIP STREET KWUN TONG KOWLOON',
  'LEVEL 88 INTERNATIONAL COMMERCE CENTRE 1 AUSTIN ROAD WEST KOWLOON',
  '11/F MAN YEE BUILDING 68 DES VOEUX ROAD CENTRAL HONG KONG',
  '11/F BANK OF CHINA CENTRE OLYMPIAN CITY 11 HOI FAI ROAD WEST KOWLOON',
  "ROOM 3908 39/F THE CENTER 99 QUEEN'S ROAD CENTRAL HONG KONG",
  '11/F FWD FINANCIAL CENTRE 308 DES VOEUX ROAD CENTRAL HONG KONG',
  "LEVEL 17 THREE PACIFIC PLACE 1 QUEEN'S ROAD EAST HONG KONG",
  '7/F TWO HARBOUR SQUARE 180 WAI YIP STREET KWUN TONG KOWLOON',
  "19/F GREENWICH CENTRE 260 KING'S ROAD NORTH POINT HONG KONG",
  '11/F CHONG HING BANK CENTRE 24 DES VOEUX ROAD CENTRAL HONG KONG',
  '41/F CENTRAL PLAZA 18 HARBOUR ROAD WANCHAI HONG KONG',
  '16/F ONE ISLAND EAST 18 WESTLANDS ROAD ISLAND EAST HONG KONG',
  '26/F CITIC TOWER 1 TIM MEI AVENUE CENTRAL HONG KONG',
  "27/F GRAND MILLENNIUM PLAZA 181 QUEEN'S ROAD CENTRAL HONG KONG",
  '11/F DUKE WELLINGTON BLDG 14-24 WELLINGTON ST CENTRAL HONG KONG',
  'RM 201-5 2/F KOWLOON CENTRE 29-39 ASHLEY ROAD KOWLOON',
  '22/F LI PO CHUN CHAMBERS 189 DES VOEUX ROAD CENTRAL HONG KONG',
  '9/F TOWER III OF ENTERPRISE SQUARE 9 SHEUNG YUET ROAD KOWLOON BAY KOWLOON',
  'LEVEL 19 28 HENNESSY ROAD HONG KONG',
  '28/F LEE GARDEN THREE 1 SUNNING ROAD CAUSEWAY BAY HONG KONG',
  "15/F CHEUNG KONG CENTER 2 QUEEN'S ROAD CENTRAL HONG KONG",
  'RM 3310 33/F BANK OF AMERICA TOWER 12 HARCOURT ROAD CENTRAL HONG KONG',
  '56-61/F INTERNATIONAL COMMERCE CENTRE 1 AUSTIN ROAD WEST KOWLOON',
  'G/F SUNSHINE MANSION 46/46A FORT STREET HONG KONG',
  'ROOM 2808 28/F CHINA MERCHANTS TOWER SHUN TAK CENTRE 168-200 CONNAUGHT ROAD CENTRAL HONG KONG',
  'SUITE 1303 TWO EXCHANGE SQUARE 8 CONNAUGHT PLACE CENTRAL HONG KONG',
  '7/F LEE GARDEN THREE 1 SUNNING ROAD CAUSEWAY BAY HONG KONG',
  '28/F THREE EXCHANGE SQUARE 8 CONNAUGHT PLACE CENTRAL HONG KONG',
  '20/F WING ON CENTRE 111 CONNAUGHT ROAD CENTRAL HONG KONG',
  "C/O BANK OF AMERICA MERRILL LYNCH 38/F CHEUNG KONG CENTER 2 QUEEN'S ROAD CENTRAL CENTRAL HONG KONG",
  'UNIT 710-715 7/F MILLENNIUM CITY 2 378 KWUN TONG ROAD KOWLOON',
  'FLAT B 11/F BEGONIA COURT WORLD WIDE GARDENS 4 LUNG PAK STREET TAI WAI NEW TERRITORIES',
  '29/F ONE INTERNATIONAL FINANCE CENTRE 1 HARBOUR VIEW STREET CENTRAL HONG KONG',
  '6/F GRAND BUILDING 15-18 CONNAUGHT ROAD CENTRAL HONG KONG',
  '5/F LUK KWOK CENTRE 72 GLOUCESTER ROAD WANCHAI HONG KONG',
  'RM 1402 FORTIS BANK TOWER 77-79 GLOUCESTER ROAD WANCHAI HONG KONG',
  'RM 1003 10/F INFINITUS PLAZA 199 DES VOEUX ROAD CENTRAL HONG KONG',
  'UNIT A 10/F YHC TOWER 1 SHEUNG YUET ROAD KOWLOON BAY KOWLOON',
  'SUITES 3207-3212 32/F ONE PACIFIC PLACE 88 QUEENSWAY HONG KONG',
  "PORTION 1 12/F THE CENTER 99 QUEEN'S ROAD CENTRAL HONG KONG",
  'UNITS 2603-2606 26/F INFINITUS PLAZA 199 DES VOEUX ROAD CENTRAL HONG KONG',
  'RM 1801-1806 PRESIDENT COMMERCIAL CENTRE 608 NATHAN ROAD MONGKOK KOWLOON',
  'RM 901-904 WORLD WIDE HOUSE 19 DES VOEUX ROAD CENTRAL HONG KONG',
  '18/F INTERNATIONAL COMMERCE CENTRE 1 AUSTIN ROAD WEST KOWLOON',
  'FLAT 33A TOWER 8 THE LEIGHTON HILL 2B BROADWOOD ROAD HAPPY VALLEY HONG KONG',
  '48/F ONE EXCHANGE SQUARE 8 CONNAUGHT ROAD CENTRAL HONG KONG',
  'UNITS 7001-06 & 7008B LEVEL 70 INTERNATIONAL COMMERCE CENTRE 1 AUSTIN ROAD WEST KOWLOON',
  'UNITS 603-605 6/F FWD FINANCIAL CENTRE 308 DES VOEUX ROAD CENTRAL SHEUNG WAN HONG KONG',
  'ROOM 1802 18/F CAPITAL CENTRE NO. 151 GLOUCESTER ROAD WANCHAI HONG KONG',
  'RM 406 4/F HOUSTON CENTRE 63 MODY ROAD TSIMSHATSUI EAST KOWLOON',
  "UNITS 2201-2207 & 2213-2214 22/F COSCO TOWER 183 QUEEN'S ROAD CENTRAL HONG KONG",
  'ROOM 1602 16/F KAI TAK COMMERCIAL BUILDING 317-319 DES VOEUX ROAD CENTRAL HONG KONG',
  "10/F NINE QUEEN'S ROAD CENTRAL HONG KONG",
  'RM 802 CHEONG K BUILDING 86 DES VOEUX ROAD CENTRAL HONG KONG',
  '28/F TWO CHINACHEM CENTRAL 26 DES VOEUX ROAD CENTRAL HONG KONG',
  '14/F GRAND BUILDING 15-18 CONNAUGHT ROAD CENTRAL HONG KONG',
  '10/F PUBLIC BANK CENTRE 120 DES VOEUX ROAD CENTRAL HONG KONG',
  'RM 2901 CHINA INSURANCE GROUP BUILDING 141 DES VOEUX ROAD CENTRAL HONG KONG',
  'SUITES 3208-3211 32/F TOWER TWO TIMES SQUARE 1 MATHESON STREET CAUSEWAY BAY HONG KONG',
  'ROOM 801-804 HALESON BUILDING 1 JUBILEE STREET CENTRAL HONG KONG',
  'RM 1101-3 11/F YARDLEY COMMERCIAL BLDG 3 CONNAUGHT ROAD WEST SHEUNG WAN HONG KONG',
  '28/F BANK OF CHINA TOWER 1 GARDEN RD CENTRAL HONG KONG',
  "RM 2001-2006 COSCO TOWER 183 QUEEN'S ROAD CENTRAL HONG KONG",
  '21/F CENTRE POINT 181-185 GLOUCESTER ROAD WANCHAI HONG KONG',
  '6/F CENTRE POINT 181-185 GLOUCESTER ROAD WANCHAI HONG KONG',
  "20/F V-HEUN BUILDING 138 QUEEN'S ROAD CENTRAL HONG KONG",
  '28/F SIU ON CENTRE 188 LOCKHART ROAD WANCHAI HONG KONG',
  '14/F OTB BUILDING 259-265 DES VOEUX ROAD CENTRAL HONG KONG',
  "RM 601-602 6/F PETER BUILDING 58-60 QUEEN'S ROAD CENTRAL HONG KONG",
  '7/F HARBOUR COMMERCIAL BUILDING 122-124 CONNAUGHT ROAD CENTRAL CENTRAL HONG KONG',
  "11/F NEW WORLD TOWER II 16-18 QUEEN'S ROAD CENTRAL  HONG KONG",
  'ROOM 2305-2306 23/F CHINA RESOURCES BUILDING 26 HARBOUR ROAD WANCHAI HONG KONG',
  '22/F MANHATTAN PLACE 23 WANG TAI ROAD KOWLOON BAY KOWLOON',
  "2/F ST. JOHN'S BUILDING 33 GARDEN ROAD CENTRAL HONG KONG",
  '39/F ONE EXCHANGE SQUARE CENTRAL HONG KONG',
  '13/F TRUST TOWER 68 JOHNSTON ROAD WANCHAI HONG KONG',
  'UNIT A 19/F DAH SING LIFE BUILDING 99 DES VOEUX ROAD CENTRAL HONG KONG',
  'UNIT B 19/F TWO CHINACHEM PLAZA 135 DES VOEUX ROAD CENTRAL HONG KONG',
  '23/F TOWER 1 ADMIRALTY CENTRE 18 HARCOURT ROAD ADMIRALTY HONG KONG',
  '7/F TOWER 1 LIPPO CENTRE 89 QUEENSWAY HONG KONG',
  'RM 304-307 CHINA INSURANCE GROUP BLDG 141 DES VOEUX ROAD CENTRAL HONG KONG',
  'UNIT A 16/F & UNIT A 17/F TWO PACIFIC PLACE 88 QUEENSWAY HONG KONG',
  'FLAT A 8/F SUI SING BUILDING 202-204 CHEUNG SHA WAN ROAD SHAMSHUIPO KOWLOON',
  '40/F LEE GARDEN ONE 33 HYSAN AVENUE CAUSEWAY BAY HONG KONG',
  'UNITS 1205-6 12/F WEST TOWER SHUN TAK CENTRE 200 CONNAUGHT ROAD CENTRAL HONG KONG',
  'ROOM 2202-3 22/F CHINA INSURANCE GROUP BUILDING 141 DES VOEUX ROAD CENTRAL HONG KONG',
  "UNIT 408-409 4/F FORTRESS TOWER 250 KING'S ROAD FORTRESS HILL HONG KONG",
  "45TH FLOOR COSCO TOWER 183 QUEEN'S ROAD CENTRAL HONG KONG",
  'RM 303-5 YUE SHING COMM. BUILDING 15-16 QUEEN VICTORIA STREET CENTRAL HONG KONG',
  "UNIT 2508 25/F COSCO TOWER 183 QUEEN'S ROAD CENTRAL CENTRAL HONG KONG",
  'FLAT B 7/F SHUN ON COMMERCIAL BUILDING 112-114 DES VOEUX ROAD CENTRAL HONG KONG',
  "ROOM 701 9 QUEEN'S ROAD CENTRAL HONG KONG",
  'FLAT F 4/F SHING LEE COMMERCIAL BUILDING 6-12 WING KUT STREET CENTRAL HONG KONG',
  "RM 5807-5812 THE CENTER 99 QUEEN'S ROAD CENTRAL HONG KONG",
  "UNITS 2401-2403 24/F GRAND MILLENNIUM PLAZA 181 QUEEN'S ROAD CENTRAL HONG KONG",
  "G/F-3/F COSCO TOWER GRAND MILLENNIUM PLAZA 183 QUEEN'S ROAD CENTRAL HONG KONG",
  "1/F WING'S BLDG 110-116 QUEEN'S ROAD CENTRAL HONG KONG",
  "18/F-19/F CHINA BUILDING 29 QUEEN'S ROAD CENTRAL HONG KONG",
  '12/F CCB TOWER 3 CONNAUGHT ROAD CENTRAL CENTRAL HONG KONG',
  'RM 1307 13/F BANK OF AMERICA TOWER 12 HARCOURT ROAD CENTRAL HONG KONG',
  'UNIT 3203 TOWER 1 ADMIRALTY CENTRE 18 HARCOURT ROAD ADMIRALTY HONG KONG',
  'RM 102 1/F ON HONG COMMERCIAL BUILDING 145 HENNESSY ROAD WANCHAI HONG KONG',
  '12/F SOUTH CHINA BUILDING 1-3 WYNDHAM STREET CENTRAL HONG KONG',
  '26/F STRAND 50 50 BONHAM STRAND SHEUNG WAN HONG KONG',
  'UNIT 1002 10/F HARBOUR EAST 218 ELECTRIC ROAD NORTH POINT HONG KONG',
  'SUITES 3201-3204 ONE EXCHANGE SQUARE 8 CONNAUGHT ROAD CENTRAL HONG KONG',
  '2/F WAH KIT COMMERCIAL CENTRE 302 DES VOEUX ROAD CENTRAL HONG KONG',
  'RM 607-610 6/F TAI YAU BUILDING 181 JOHNSTON ROAD WANCHAI HONG KONG',
  'ROOM 1201-02 12/F TUNG HIP COMMERCIAL BUILDING 252 DES VOEUX ROAD CENTRAL HONG KONG',
  'RM 2501 25/F AIA TOWER 183 ELECTRIC ROAD NORTH POINT HONG KONG',
  'RM 1803 YUE SHING COMM BLDG 15 QUEEN VICTORIA ST CENTRAL HONG KONG',
  'FLAT A & B 7/F NGAN HOUSE 210 DES VOEUX ROAD CENTRAL HONG KONG',
  '1/F CHUN WO COMMERCIAL CENTRE 23-29 WING WO STREET CENTRAL HONG KONG',

In [77]:
import time

In [72]:
def get_driver(url):
    _driver = webdriver.Chrome(os.getcwd()+'/chromedriver')
    _driver.get(url)
    
    return _driver

In [80]:
driver.close()

MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52951): Max retries exceeded with url: /session/197f01cf6ec6c175add52fb0ab361d8f/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18f7995550>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [79]:
%%time
URL = "https://www.hkexnews.hk/sdw/search/searchsdw.aspx"

driver = get_driver(URL) 
for d in date_list:
    stock_code_list = get_stock_code_list(d)
    for s in stock_code_list:
        driver.execute_script(f"document.getElementById('txtShareholdingDate').value='{d}'")
        driver.execute_script(f"document.getElementById('txtStockCode').value='{s}'")
        driver.find_element_by_id('btnSearch').click()
        print(f"document.getElementById('txtShareholdingDate').value='{d}'")
        time.sleep(1)

document.getElementById('txtShareholdingDate').value='2021/06/15'
document.getElementById('txtShareholdingDate').value='2021/06/15'
document.getElementById('txtShareholdingDate').value='2021/06/15'
document.getElementById('txtShareholdingDate').value='2021/06/15'
document.getElementById('txtShareholdingDate').value='2021/06/15'
document.getElementById('txtShareholdingDate').value='2021/06/15'
document.getElementById('txtShareholdingDate').value='2021/06/15'
document.getElementById('txtShareholdingDate').value='2021/06/15'

KeyboardInterrupt:

In [79]:
int(summary[0].select_one('div.summary-value').get_text().replace(',',''))

1361618242

In [21]:
date.setAttribute('value','2021/06/18')

AttributeError: 'WebElement' object has no attribute 'setAttribute'

In [1]:
import os

In [5]:
dates = os.listdir('summary')

In [9]:
dates.sort()

In [14]:
dates

['20210615', '20210616', '20210617', '20210618']

In [15]:
fns = os.listdir('summary/'+dates[0])

In [16]:
fns.sort()
fns

['00001.csv',
 '00002.csv',
 '00003.csv',
 '00004.csv',
 '00005.csv',
 '00006.csv',
 '00007.csv',
 '00008.csv',
 '00009.csv',
 '00010.csv',
 '00011.csv',
 '00012.csv',
 '00014.csv',
 '00016.csv',
 '00017.csv',
 '00018.csv',
 '00019.csv',
 '00021.csv',
 '00022.csv',
 '00023.csv',
 '00024.csv',
 '00025.csv',
 '00026.csv',
 '00027.csv',
 '00028.csv',
 '00029.csv',
 '00030.csv',
 '00031.csv',
 '00032.csv',
 '00033.csv',
 '00034.csv',
 '00035.csv',
 '00036.csv',
 '00037.csv',
 '00038.csv',
 '00039.csv',
 '00040.csv',
 '00041.csv',
 '00042.csv',
 '00043.csv',
 '00045.csv',
 '00046.csv',
 '00047.csv',
 '00048.csv',
 '00050.csv',
 '00051.csv',
 '00052.csv',
 '00053.csv',
 '00055.csv',
 '00057.csv',
 '00058.csv',
 '00059.csv',
 '00060.csv',
 '00061.csv',
 '00062.csv',
 '00063.csv',
 '00064.csv',
 '00065.csv',
 '00066.csv',
 '00067.csv',
 '00068.csv',
 '00069.csv',
 '00070.csv',
 '00071.csv',
 '00072.csv',
 '00073.csv',
 '00075.csv',
 '00076.csv',
 '00077.csv',
 '00078.csv',
 '00079.csv',
 '00080.csv',
 '00081.csv',
 '00082.csv',
 '00083.csv',
 '00084.csv',
 '00085.csv',
 '00086.csv',
 '00087.csv',
 '00088.csv',
 '00089.csv',
 '00090.csv',
 '00091.csv',
 '00092.csv',
 '00093.csv',
 '00094.csv',
 '00095.csv',
 '00096.csv',
 '00097.csv',
 '00098.csv',
 '00099.csv',
 '00100.csv']

In [17]:
def get_summary_files():
    pass

In [39]:
# _dir = 'summary'
def generate_file_list(_dir):
    dates = os.listdir(_dir)
    dates.sort()
    dw_fl = []
#     print(dates)
    for d in dates:
        
        fl = []
        fns = os.listdir(f'{_dir}/{d}')
        fns.sort()
#         print(fns)
        for fn in fns:
            fl.append(f'{_dir}/{d}/{fn}')
        dw_fl.append(fl)
        
    return dw_fl

In [48]:
dw_fl = generate_file_list('summary')

In [49]:
import pandas as pd

In [53]:
# cdf = pd.DataFrame({})
def combine_summary():
    dw_fl = generate_file_list('summary') 
    for fl in dw_fl:
        dfl = []
        for fn in fl:
            df = pd.read_csv(fn)
            dfl.append(df)
        dw_df = pd.concat(dfl).reset_index(drop=True)
        columns = list(dw_df.columns)
        dw_df = dw_df[columns[-2:]+columns[:-2]]
        os.makedirs('_summary',exist_ok=True)
        _fn = f'_summary/{fl[0].split("/")[1]}.csv'
        print(_fn)
        dw_df.to_csv(_fn,index=False)

In [109]:
def combine_table():
    dw_fl = generate_file_list('table') 
    for fl in dw_fl:
        dfl = []
        for fn in fl:
            df = pd.read_csv(fn)
            dfl.append(df)
            
        dw_df = pd.concat(dfl).reset_index(drop=True)
        cn = list(dw_df.columns)
        
        pot = dw_df[cn[:3]]
        pot = pot.drop_duplicates(cn[0]).reset_index(drop=True)
        
        dw_df = dw_df[cn[-2:]+cn[:1]+cn[3:-2]]
        print(cn)
        os.makedirs('_table',exist_ok=True)
        _fn = f'_table/{fl[0].split("/")[1]}.csv'
        print(_fn)
        dw_df.to_csv(_fn,index=False)
        
        _fnp = f'_table/p_id_{fl[0].split("/")[1]}.csv'
        print(_fnp)
        pot.to_csv(_fnp,index=False)

In [110]:
combine_table()

['Participant ID', 'Name of CCASS Participant(* for Consenting Investor Participants )', 'Address', 'Shareholding', '% of the total number of Issued Shares/ Warrants/ Units', 'Date', 'Stock code']
_table/20210615.csv
_table/p_id_20210615.csv
['Participant ID', 'Name of CCASS Participant(* for Consenting Investor Participants )', 'Address', 'Shareholding', '% of the total number of Issued Shares/ Warrants/ Units', 'Date', 'Stock code']
_table/20210616.csv
_table/p_id_20210616.csv
['Participant ID', 'Name of CCASS Participant(* for Consenting Investor Participants )', 'Address', 'Shareholding', '% of the total number of Issued Shares/ Warrants/ Units', 'Date', 'Stock code']
_table/20210617.csv
_table/p_id_20210617.csv
['Participant ID', 'Name of CCASS Participant(* for Consenting Investor Participants )', 'Address', 'Shareholding', '% of the total number of Issued Shares/ Warrants/ Units', 'Date', 'Stock code']
_table/20210618.csv
_table/p_id_20210618.csv

In [111]:
pd.read_csv('_table/p_id_20210618.csv')

,Participant ID,Name of CCASS Participant(* for Consenting Investor Participants ),Address
0,C00019,THE HONGKONG AND SHANGHAI BANKING,HSBC WEALTH BUSINESS SERVICES 8/F TOWER 2 & 3 ...
1,C00100,"JPMORGAN CHASE BANK, NATIONAL",18/F TOWER 2 THE QUAYSIDE 77 HOI BUN ROAD KWUN...
2,C00010,CITIBANK N.A.,9/F CITI TOWER ONE BAY EAST 83 HOI BUN ROAD KW...
3,C00039,STANDARD CHARTERED BANK (HONG KONG) LTD,18/F STANDARD CHARTERED BANK TOWER MILLENNIUM ...
4,C00018,HANG SENG BANK LTD,16/F HANG SENG 113 113 ARGYLE STREET MONGKOK K...
...,...,...,...
597,B01068,TEIL STOCK INVESTMENT CO (ADMINISTRATORS,C/O JOINT AND SEVERAL ADMINISTRATORS DELOITTE ...
598,B01474,VICTORFIELD SECURITIES LTD,UNIT 902 9/F AON CHINA BUILDING 29 QUEEN'S ROA...
599,B01635,TAI WAH SECURITIES LTD,RM 1001-3 YU TO SANG BUILDING 37 QUEEN'S ROAD ...
600,B02142,OCEAN JOY SECURITIES LIMITED,18/F CENTRAL 88 88-98 DES VOEUX ROAD CENTRAL H...
601,B01899,SANSTON FINANCIAL GROUP LTD,17/F THE L. PLACE 139 QUEEN'S ROAD CENTRAL HON...

In [104]:
aa = pd.read_csv('_table/20210615.csv')

In [105]:
aa.head()

,Date,Stock code,Participant ID,Shareholding,% of the total number of Issued Shares/ Warrants/ Units
0,2021-06-15,1,C00019,"1,227,603,432",31.83%
1,2021-06-15,1,C00100,"295,698,691",7.66%
2,2021-06-15,1,C00010,"257,112,829",6.66%
3,2021-06-15,1,C00039,"154,761,335",4.01%
4,2021-06-15,1,C00018,"68,011,099",1.76%

In [72]:
cn = list(aa.columns)

In [76]:
pot = aa[cn[2:5]]

In [86]:
pot

,Participant ID,Name of CCASS Participant(* for Consenting Investor Participants ),Address
0,C00019,THE HONGKONG AND SHANGHAI BANKING,HSBC WEALTH BUSINESS SERVICES 8/F TOWER 2 & 3 ...
1,C00100,"JPMORGAN CHASE BANK, NATIONAL",18/F TOWER 2 THE QUAYSIDE 77 HOI BUN ROAD KWUN...
2,C00010,CITIBANK N.A.,9/F CITI TOWER ONE BAY EAST 83 HOI BUN ROAD KW...
3,C00039,STANDARD CHARTERED BANK (HONG KONG) LTD,18/F STANDARD CHARTERED BANK TOWER MILLENNIUM ...
4,C00018,HANG SENG BANK LTD,16/F HANG SENG 113 113 ARGYLE STREET MONGKOK K...
...,...,...,...
20821,B01818,I-ACCESS INVESTORS LTD,SUITES 3208-3211 32/F TOWER TWO TIMES SQUARE 1...
20822,B01459,IFAST SECURITIES (HK) LTD,SUITE 1303 TWO EXCHANGE SQUARE 8 CONNAUGHT PLA...
20823,B01904,VALUABLE CAPITAL LTD,ROOM 2808 28/F CHINA MERCHANTS TOWER SHUN TAK ...
20824,C00041,OCBC WING HANG BANK LTD,UNIT 1702 17/F EASTERN CENTRAL PLAZA 3 YIU HIN...
20825,B01769,ONE CHINA SECURITIES LTD,2/F CHEONG K. BUILDING 84-86 DES VOEUX ROAD CE...

In [87]:
pot.drop_duplicates(cn[2])

,Participant ID,Name of CCASS Participant(* for Consenting Investor Participants ),Address
0,C00019,THE HONGKONG AND SHANGHAI BANKING,HSBC WEALTH BUSINESS SERVICES 8/F TOWER 2 & 3 ...
1,C00100,"JPMORGAN CHASE BANK, NATIONAL",18/F TOWER 2 THE QUAYSIDE 77 HOI BUN ROAD KWUN...
2,C00010,CITIBANK N.A.,9/F CITI TOWER ONE BAY EAST 83 HOI BUN ROAD KW...
3,C00039,STANDARD CHARTERED BANK (HONG KONG) LTD,18/F STANDARD CHARTERED BANK TOWER MILLENNIUM ...
4,C00018,HANG SENG BANK LTD,16/F HANG SENG 113 113 ARGYLE STREET MONGKOK K...
...,...,...,...
17633,B02166,HTF SECURITIES LTD,ROOM 1807 18/F OFFICE TOWER CONVENTION PLAZA 1...
17879,B01068,TEIL STOCK INVESTMENT CO (ADMINISTRATORS,C/O JOINT AND SEVERAL ADMINISTRATORS DELOITTE ...
20165,B01474,VICTORFIELD SECURITIES LTD,UNIT 902 9/F AON CHINA BUILDING 29 QUEEN'S ROA...
20166,B01635,TAI WAH SECURITIES LTD,RM 1001-3 YU TO SANG BUILDING 37 QUEEN'S ROAD ...
20582,B01899,SANSTON FINANCIAL GROUP LTD,17/F THE L. PLACE 139 QUEEN'S ROAD CENTRAL HON...

In [27]:
pd.concat(dfl).reset_index(drop=True)

,Market Intermediaries,Consenting Investor Participants,Non-consenting Investor Participants,Total,Total number of Issued Shares/Warrants/Units (last updated figure),Date,Stock code
0,"['2,549,728,431', '411', '66.12%']","['71,252', '13', '0.00%']","['15,666,171', '955', '0.40%']","['2,565,465,854', '1,379', '66.52%']",3856040500,2021-06-15,1
0,"['1,369,632,915', '368', '54.21%']","['2,807,474', '11', '0.11%']","['14,116,412', '649', '0.55%']","['1,386,556,801', '1,028', '54.87%']",2526450570,2021-06-15,2
0,"['8,897,981,746', '437', '50.06%']","['914,710', '16', '0.00%']","['89,782,078', '937', '0.50%']","['8,988,678,534', '1,390', '50.56%']",17771304856,2021-06-15,3
0,"['1,570,479,024', '296', '51.41%']","['18,375', '3', '0.00%']","['9,228,025', '159', '0.30%']","['1,579,725,424', '458', '51.71%']",3054227327,2021-06-15,4
0,"['10,026,688,510', '529', '48.31%']","['647,234', '45', '0.00%']","['86,229,744', '3,101', '0.41%']","['10,113,565,488', '3,675', '48.72%']",20751319035,2021-06-15,5
...,...,...,...,...,...,...,...
0,"['156,156,096', '38', '24.53%']",NaN,NaN,"['156,156,096', '38', '24.53%']",636549600,2021-06-15,96
0,"['834,612,281', '244', '27.38%']",NaN,"['51,367,635', '94', '1.68%']","['885,979,916', '338', '29.06%']",3047327395,2021-06-15,97
0,"['270,991,134', '85', '64.63%']",NaN,"['22,459,000', '5', '5.35%']","['293,450,134', '90', '69.98%']",419248334,2021-06-15,98
0,"['133,740,982', '106', '27.95%']",NaN,"['36,493,441', '22', '7.62%']","['170,234,423', '128', '35.57%']",478483794,2021-06-15,99
0,"['65,419,478', '38', '12.07%']",NaN,"['7,000', '2', '0.00%']","['65,426,478', '40', '12.07%']",541700500,2021-06-15,100